### ISSUE TITLE
Readme mistake

### ISSUE THREAD

**Issue by szyminson** [hypefactors/laravel-follow#2]
Hi, 
I think there's a mistake in [*Preparing the Eloquent Models*](https://github.com/hypefactors/laravel-follow#preparing-the-eloquent-models) section of readme. 
Instead of 
```php
use Hypefactors\Laravel\Follow\CanFollow;
```
It should be
```php
use Hypefactors\Laravel\Follow\Traits\CanFollow;
```
And the same for `CanBeFollowed` Trait. Otherwise *Trait not found* exception is returned.

**Comment by brunogaspar** [comment]
Good catch @szyminson 

Going to fix it, thanks!
